/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b5973ec4474a1d976c716273a5bdb682)
interface __BaseEnv_Env {
  RATES_KV: KVNamespace
  ASSETS: Fetcher
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./dist/server/index")
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
